"""Initial

Revision ID: 45cadfe3ad1d
Revises: 
Create Date: 2023-09-15 08:26:03.266023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45cadfe3ad1d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('tag_name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('twitch_games',
    sa.Column('game_name', sa.String(), nullable=False),
    sa.Column('twitch_game_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_twitch_games_twitch_game_id'), 'twitch_games', ['twitch_game_id'], unique=False)
    op.create_table('twitch_users',
    sa.Column('twitch_user_id', sa.BigInteger(), nullable=True),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('broadcaster_type', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_twitch_users_twitch_user_id'), 'twitch_users', ['twitch_user_id'], unique=False)
    op.create_table('twitch_streams',
    sa.Column('twitch_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('stream_title', sa.String(), nullable=True),
    sa.Column('viewer_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['twitch_games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['twitch_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_twitch_streams_twitch_id'), 'twitch_streams', ['twitch_id'], unique=False)
    op.create_table('stream_tag',
    sa.Column('stream_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['twitch_streams.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stream_tag')
    op.drop_index(op.f('ix_twitch_streams_twitch_id'), table_name='twitch_streams')
    op.drop_table('twitch_streams')
    op.drop_index(op.f('ix_twitch_users_twitch_user_id'), table_name='twitch_users')
    op.drop_table('twitch_users')
    op.drop_index(op.f('ix_twitch_games_twitch_game_id'), table_name='twitch_games')
    op.drop_table('twitch_games')
    op.drop_table('tags')
    # ### end Alembic commands ###
